{% set version = "2.1.7" %}

package:
  name: cchardet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cchardet/cchardet-{{ version }}.tar.gz
  sha256: c428b6336545053c2589f6caf24ea32276c6664cb86db817e03a94c60afa0eaf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cchardet

about:
  home: https://github.com/PyYoshi/cChardet
  license_file: COPYING
  license: GPL-3.0
  license_family: GPL
  summary: cChardet is high speed universal character encoding detector
  dev_url: https://github.com/PyYoshi/cChardet
  doc_url: https://github.com/PyYoshi/cChardet

extra:
  recipe-maintainers:
    - pmlandwehr
    - Ryan-Dmello
